---
title: "Exercises"
output: html_document
---

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org/"))

# Install the dplyr package if not already installed
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
```

```{r}
install.packages("dplyr")
```

```{r}
library(dplyr)
```

```{r}
tree_dat <- read.csv("~/github/Lab 2/data/data1/data2.R1/tree_dat.csv")
```

```{r}
#1
library(dplyr)
tree_dat %>% summarise(n=n())
```

```{r}
nrow(tree_dat)
```

```{r}
#2
tree_dat %>%
  filter(standID == 1) %>%
  tally()
  
```

```{r}
tree_count1 <- tree_dat %>%
  filter(standID == 1)

print(tree_count1)
```

```{r}
#3
tree_dat %>%
  filter(species %in% c("ABBA", "PIST")) %>%
  count(species)
```

```{r}
#4
last_year <- max(tree_dat$year, na.rm = TRUE)
tree_dat %>%
  filter(year == last_year, age > 200) %>%
  tally()
```

```{r}
#5
tree_dat %>%
  slice_max(order_by = age, n = 1)
oldest_tree <- tree_dat %>%
  slice_max(order_by = age, n = 1)

print(oldest_tree)

```

```{r}
#6
tree_dat %>%
  filter(year == 2001) %>%
  slice_max(order_by = age, n = 5)

oldest_trees_2001 <- tree_dat %>%
  filter(year == 2001) %>%
  slice_max(order_by = age, n = 5)
```

```{r}
#7
tree_dat %>% filter(year == 2002) %>%
  slice_sample(prop = 0.3) %>%
  summarise(n = n())
```

```{r}
#8
library(dplyr)

tree_dat %>% filter(year == 2007) %>%
  filter(standID == 5) %>%
  arrange(desc(rad_ib)) %>%
  slice_head(n = 3) %>%
  select(treeID)
```

```{r}
#9
library(dplyr)

smallest_stand3 <- tree_dat %>%
  select(treeID, stand, year, rad_ib) %>%
  filter(stand == "3", year == 2007) %>%
  slice_min(order_by = rad_ib, n = 3)

smallest_stand3

```

```{r}
#10
trees_no_stand <- tree_dat %>%
  select(-stand)

glimpse(trees_no_stand)

```

```{r}
#11
id_columns <- tree_dat %>%
  select(matches("ID"))

head(id_columns)

```

```{r}
#12
selected_columns <- tree_dat |>
  select(matches("ID|stand"))

glimpse(selected_columns)

```

```{r}
#13
tree_dat <- tree_dat %>%
  rename(
    rad_ib_mm = rad_ib,   
    inc_mm = inc          
  )


glimpse(tree_dat)

```

```{r}
#14
library(dplyr)

tree_dat <- tree_dat |>
  mutate(
    DBH_cm = 2 * rad_ib_mm,
    BA_m2 = 0.00007854 * DBH_cm^2
  ) |>
  filter(species == "POTR", year == 2007) |>  
  summarise(mean_BA_m2 = mean(BA_m2))

tree_dat

```


```{r}
#15
library(dplyr)

tree_count1 <- tree_count1 %>%
  mutate(
    established = if_else(age > 5, TRUE, FALSE)
  )

established_count <- tree_count1 %>%
  count(established)

print(established_count)

```



```{r}
#15
tree_count1 <- tree_count1 %>%
  mutate(
    established = if_else(age > 5, TRUE, FALSE)
    )
  established_count <- tree_count1 %>%
  count(established)

```



```{r}
#16
library(dplyr)

tree_count1 <- tree_count1 |>
  mutate(
    DBH_cm = 2 * rad_ib,  
    DBH_class = case_when(
      DBH_cm > 0 & DBH_cm <= 2.5 ~ "seedling",   
      DBH_cm > 2.5 & DBH_cm <= 10 ~ "sapling",    
      DBH_cm > 10 & DBH_cm <= 30 ~ "pole",       
      DBH_cm > 30 ~ "sawlog",                     
      TRUE ~ NA_character_                      
    )
  ) |>
  filter(year == 2007) |>  
  count(DBH_class)  

tree_count1

```

```{r}
#17
library(dplyr)

dbh_stats <- tree_dat1 |>
  filter(year == 2007) |>
  mutate(DBH_cm = (rad_ib_mm * 2) / 10) |>
  summarise(mean_DBH_cm = mean(DBH_cm, na.rm = TRUE), sd(DBH_cm, na.rm = TRUE))

dbh_stats
```

```{r}
#18
library(dplyr)

tree_dat_summary <- tree_dat1 |>
  filter(year == 2003) |> 
  group_by(species) |>
  summarize(mean_age = mean(age, na.rm = TRUE)) |> 
  arrange(desc(mean_age)) |>
  slice_head(n = 3)  

tree_dat_summary

```

```{r}
#19
library(dplyr)

tree_dat_summary <- tree_dat1 |>
  summarize(
    unique_years = n_distinct(year), 
    first_year = min(year), 
    last_year = max(year)
  )

tree_dat_summary

```

```{r}
#20
library(dplyr)

stand_years_summary <- tree_dat1 |>
  group_by(stand) |>  
  summarize(unique_years = n_distinct(year), .groups = "drop") |>  
  
  arrange(desc(unique_years))  

max_unique_years <- max(stand_years_summary$unique_years)

stands_with_largest_record <- stand_years_summary |>
  filter(unique_years == max_unique_years)

stands_with_largest_record

```

```{r}
#FINAL QUESTION

library(dplyr) 

tree_growth <- tree_dat1 %>% 
  arrange(treeID, year) %>% 
  group_by(treeID) %>% 
  mutate(annual_growth = rad_ib_mm - lag(rad_ib_mm)) %>% filter(!is.na(annual_growth)) 


tree_summary <- tree_growth %>% 
  summarise(total_years = n(), avg_annual_growth = mean(annual_growth, na.rm = TRUE)) %>% 
  filter(total_years >= 10) 


species_growth <- tree_summary %>% 
  left_join(tree_dat1 %>% 
              select(treeID, species), by = "treeID") %>% 
  group_by(species) %>% 
  summarise( avg_species_growth = mean(avg_annual_growth, na.rm = TRUE), sd_species_growth = sd(avg_annual_growth, na.rm = TRUE), .groups = 'drop' ) 


fastest_species <- species_growth %>% 
  arrange(desc(avg_species_growth)) %>% 
  slice_head(n = 3) 


slowest_species <- species_growth %>% 
  arrange(avg_species_growth) %>% 
  slice_head(n = 3) 


print("Fastest Growing Species:") 
print(fastest_species) 
print("Slowest Growing Species:") 
print(slowest_species) 
```

```{r}

list.files("image")

library(magick)

image <- image_read("image/PIRE.jpg")

image


```
